export enum Technology {
    Typescript = 'Typescript',
    React = 'React',
    Node = 'Node',
    Jest = 'Jest',
    Git = 'Git',
    Linux = 'Linux',
    SQL = 'SQL',
    AWS = 'AWS',
    PHP = 'PHP',
    Python = 'Python',
    Laravel = 'Laravel',
    PHPUnit = 'PHPUnit',
    Docker = 'Docker',
    GoogleAppScript = 'Google App Script',
    HTML = 'HTML',
    CSS = 'CSS',
    JS = 'JS',
    Tailwind = 'Tailwind',
    GoogleSheets = 'Google Sheets',
    TensorFlow = 'TensorFlow',
    Vim = 'Vim',
    NeoVim = 'NeoVim',
}
