import Image from "next/image";
import { Logos } from "@/components/Logos";
import { ProfileImage } from "@/components/ProfileImage";

export default function Jobs() {
  return (
    <div className="flex justify-center py-20 font-mono">
      <div className="bg-white p-5 rounded-xl w-1/2">
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
        <div>something</div>
      </div>
    </div>
  );
}
