/**
 * Remove generated files from public/.
 *
 * - public/img/*  (regenerated by `npm run images`)
 * - any *.br and *.gz pre-compressed files
 *
 * Use before a fresh build:  npm run clean
 */

import { readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUBLIC = join(__dirname, '..', 'public');

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(path);
    else yield path;
  }
}

async function main() {
  let removed = 0;

  // Drop the entire generated image directory.
  try {
    await rm(join(PUBLIC, 'img'), { recursive: true, force: true });
    console.log('  removed public/img/');
    removed++;
  } catch {}

  // Drop pre-compressed files anywhere under public/.
  for await (const path of walk(PUBLIC)) {
    if (path.endsWith('.br') || path.endsWith('.gz')) {
      await rm(path);
      removed++;
    }
  }

  console.log(`Cleaned ${removed} item(s).`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
